GET http://localhost:8080/security-info/roles-allowed
Content-Type: */*
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuc2NodWx1bmdlbi5kZS9pc3N1ZXIiLCJ1cG4iOiJyYWxmLnVlYmVyZnVockBhcnMuZGUiLCJncm91cHMiOlsiVXNlciIsIkFkbWluIl0sImJpcnRoZGF0ZSI6IjE5ODEtMTAtMTEiLCJpYXQiOjE3MTg4NTg5ODcsImV4cCI6MTcxODg1OTI4NywianRpIjoiZGQzZmUxM2EtZDQyMy00NmI2LTk5MmYtNGZhODc0MzcxZDFlIn0.EN3ko_aUQNseEe3RoMeKJU3hyy3KDXZ-egqomjuleGUsGxlDxs8CZeQxZExYOC6EjyTyW4Uf_hZ_NRphKUrym1oLWxNpTR7VmEYkHtjwA9IFGAjmRTU7bVvvD8ez3cOntDK79NdZncHtV5eOoNugS96qI11lg5syYoeC56bp4eNZmli5Wgl75-WF2aX5CdVvHrwqZOmiqKyfjWyq4Ww6WuJ8udv66vDT0HGrrvvm6OcvY7afyEDrAIJTbFvT0Vnjrd69Nl5REyDPuwCrQqQTZiDH6a73RHwYlgZykWs1hMr2AhBfEt2igXGrS23FV3OU_pSx9o3J8zsNFxIq0n45xw

###

GET http://localhost:8080/security-info/roles-allowed-admin
Content-Type: */*
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuc2NodWx1bmdlbi5kZS9pc3N1ZXIiLCJ1cG4iOiJyYWxmLnVlYmVyZnVockBhcnMuZGUiLCJncm91cHMiOlsiVXNlciIsIkFkbWluIl0sImJpcnRoZGF0ZSI6IjE5ODEtMTAtMTEiLCJpYXQiOjE3MTg4NTg5ODcsImV4cCI6MTcxODg1OTI4NywianRpIjoiZGQzZmUxM2EtZDQyMy00NmI2LTk5MmYtNGZhODc0MzcxZDFlIn0.EN3ko_aUQNseEe3RoMeKJU3hyy3KDXZ-egqomjuleGUsGxlDxs8CZeQxZExYOC6EjyTyW4Uf_hZ_NRphKUrym1oLWxNpTR7VmEYkHtjwA9IFGAjmRTU7bVvvD8ez3cOntDK79NdZncHtV5eOoNugS96qI11lg5syYoeC56bp4eNZmli5Wgl75-WF2aX5CdVvHrwqZOmiqKyfjWyq4Ww6WuJ8udv66vDT0HGrrvvm6OcvY7afyEDrAIJTbFvT0Vnjrd69Nl5REyDPuwCrQqQTZiDH6a73RHwYlgZykWs1hMr2AhBfEt2igXGrS23FV3OU_pSx9o3J8zsNFxIq0n45xw
